### ISSUE TITLE
Question regarding the threat model

### ISSUE THREAD

**Issue by openbbox** [inspire-group/PatchGuard#1]
Thanks for sharing the implementation.

While I was running the code, I found the generated adversarial patches are completely different for different input samples. The threat model used in the paper seems to be a per-instance patch, which is different from the original _Adversarial Patch_ paper. In _Adversarial Patch_, it claims "this attack generates an image-independent patch that is extremely salient to a neural network". Also, in _LaVAN: Localized and Visible Adversarial Noise_, authors observe that, for per-instance patches, "attempting to move the noise to a different image fail". A transferable/universal noise is then discussed in the paper. However, I did not find any discussion in the paper regarding this.

It would be really appreciated if this can be clarified.

**Comment by xiangchong1** [comment]
1. Yes, `patch_attack.py` only gives you a patch that works for a specific location at a specific image. This is a simple script I wrote to show the vulnerability of ML models, and it is **not used in any part of our defense evaluation**.
2. As for the threat model, the only assumption we made is the size/shape of the patch. _The patch can be anywhere on the image, can be a targeted attack or untargeted attack, can be universal or non-universal._ Our defense analysis (Algorithm 2) has a provable security guarantee (Theorem 1). That is, as long as 1) all adversarial perturbations are within one restricted region, and 2) Algorithm 2 returns True (certifies the robustness), PatchGuard can always give correct classification output. **This robustness property is agnostic to attack strategies, objectives, etc.**
